---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: latest

inputs:
- name: resource-git-onboarding_ui

run:
  path: resource-git-onboarding_ui/ci/tasks/run-test.sh
